// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Jdl91NyLV9kuZBeCv97WA02fwcCocmw',
    appId: '1:1063612597347:web:0f01e02ee896e39e9b2456',
    messagingSenderId: '1063612597347',
    projectId: 'aura-health-87001',
    authDomain: 'aura-health-87001.firebaseapp.com',
    storageBucket: 'aura-health-87001.firebasestorage.app',
    measurementId: 'G-QFB91F24PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF4SKU6lRF2NQaG9kiTwcmo-PN3yIbQkw',
    appId: '1:1063612597347:android:bef04bf523a359659b2456',
    messagingSenderId: '1063612597347',
    projectId: 'aura-health-87001',
    storageBucket: 'aura-health-87001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfkVkBIL-PpDwcP1PYjLVQiCyKpbqRy6I',
    appId: '1:1063612597347:ios:538ef668b324b1f19b2456',
    messagingSenderId: '1063612597347',
    projectId: 'aura-health-87001',
    storageBucket: 'aura-health-87001.firebasestorage.app',
    iosBundleId: 'com.aurahealth.auraHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfkVkBIL-PpDwcP1PYjLVQiCyKpbqRy6I',
    appId: '1:1063612597347:ios:538ef668b324b1f19b2456',
    messagingSenderId: '1063612597347',
    projectId: 'aura-health-87001',
    storageBucket: 'aura-health-87001.firebasestorage.app',
    iosBundleId: 'com.aurahealth.auraHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Jdl91NyLV9kuZBeCv97WA02fwcCocmw',
    appId: '1:1063612597347:web:1ec4bf62d8681af29b2456',
    messagingSenderId: '1063612597347',
    projectId: 'aura-health-87001',
    authDomain: 'aura-health-87001.firebaseapp.com',
    storageBucket: 'aura-health-87001.firebasestorage.app',
    measurementId: 'G-ZRLXZHM8N8',
  );
}
